name: call deployment pipeline
on:
  workflow_dispatch:
    inputs:
      committed_sha:
        description: "Hash to deploy"
        type: string
        required: true
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call_deployment_pipeline:
    name: Execute Deployment
    environment:
      name: development
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Run github workflow
     #if: startsWith(github.event.head_commit.message, 'deploy')
     # run: curl -X POST ${{ env.DISPATCH_URL }} -H '${{ env.HEADERS }}' -d '${{ env.BODY }}'
        run: curl 'https://dm-us.informaticacloud.com/saas/public/core/v3/login' \
    --header 'Accept: application/json'\
    --header 'Content-Type: application/json' \
    --data-raw 'username: IICS_DEV_USER' \
    --data-raw 'password: 4IICS@Dev'
