name: call deployment pipeline

# Controls when the workflow will run
on:
  push:
    branches:
      - 'dev'
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
    

env:
  DISPATCH_URL: "https://api.github.com/repos/brandon-bird-inf/iics-promotion-pipeline/actions/workflows/iics_deployment.yml/dispatches"
  HEADERS: "Authorization: Bearer ${{ secrets.CICD_TRIGGER_SECRET }}" 
  BODY: '{ "ref":"main", "inputs":{"committed_sha":"${{ github.sha }}"}}'
  JENKINS_URL: http://vm-cicd-all-ip.eastus.cloudapp.azure.com:8080/job/infa_pipeline/buildWithParameters
  AZDO_URL: https://dev.azure.com/diteam-dataops/iics-diteam/_apis/pipelines/9/runs?api-version=6.0-preview.1
  AZDO_HEADERS: "Content-Type: application/json"
  AZDO_BODY: '{ "templateParameters": {"COMMIT_HASH": "${{ github.sha }}"} }'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      id: myRequest
      uses: sanjeevk-dwh/fjogeleit_http-request-action@v1
   
      with:
        url: 'https://na1.dm-us.informaticacloud.com/active-bpel/rt/sanjeev_test'
        method: 'POST'
        username: 'IICS_DEV_USER'
        password: '4IICS@Dev'
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"Name":"Sanjeev"}'
    
    - name: Show Response
      run: |
        echo ${{ steps.myRequest.outputs.response }}
        echo ${{ steps.myRequest.outputs.headers }}
